import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {GetStaticPaths, GetStaticProps} from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

const inter = Inter({ subsets: ['latin'] })

export type HomePageProps = {
  username: string;
  cmsContent?: string;
};

export default function Home({ username, cmsContent = '' }: HomePageProps) {
  const { t } = useTranslation('pages/homepage');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>{t('homepage.welcome')} {username}!</h1>
        <h2>{cmsContent}</h2>
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps<any, { hp_slug: string }, any> = async ({
  params: { hp_slug = 'desktop' } = { hp_slug: 'desktop' },
  locale = 'en-US',
}) => {
  console.log('getStaticProps invoked');

  // simulating cms api call:
  const content = await new Promise((resolve) => {
    setTimeout(() => {
      resolve(hp_slug === 'desktop'
        ? `Enjoy the desktop version. And this is your number: ${Math.round(Math.random() * 100)}`
        : `Enjoy the mobile version. And this is your number: ${Math.round(Math.random() * 100)}`
      );
    }, 200);
  });

  return {
    props: {
      username: 'Elliott',
      cmsContent: content,
      ...(await serverSideTranslations(locale, ['pages/homepage'])),
    },
  };
};

export const getStaticPaths: GetStaticPaths = async ({ locales, defaultLocale }) => {
  console.log('getStaticPaths invoked');
  return {
    paths: [
      {
        params: { hp_slug: 'desktop' },
        locale: 'en-US',
      },
      {
        params: { hp_slug: 'desktop' },
        locale: 'zh-CN',
      },
      {
        params: { hp_slug: 'mobile' },
        locale: 'en-US',
      },
      {
        params: { hp_slug: 'mobile' },
        locale: 'zh-CN',
      },
    ],
    fallback: true,
  };
};
